package Cajero;

import Conexion_bd.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Miguel
 */
public class Introducir_PIN extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Introducir_PIN(String ID_Tarjeta, Idioma idioma) {
        initComponents();
        this.ID_Tarjeta = ID_Tarjeta;
        this.idioma = idioma;
        cargarIdioma(idioma);
        jPanel2.setBackground(new Color(0, 0, 0, 0));
    }
    public void cargarIdioma(Idioma idioma){
        Properties propiedades = new Idioma(idioma.getNombre());
        this.setTitle(propiedades.getProperty("Introducir_PIN"));
        lblIntroduce.setText(propiedades.getProperty("Introduce2"));
        lblPIN.setText(propiedades.getProperty("PIN"));
        btnRetroceder.setText(propiedades.getProperty("btnRetroceder"));
        btnAcceder.setText(propiedades.getProperty("btnAcceder"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfPIN = new javax.swing.JPasswordField();
        lblIntroduce = new javax.swing.JLabel();
        lblPIN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCajero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRetroceder = new javax.swing.JButton();
        btnAcceder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnAsterisco = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(102, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txfPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, -1));

        lblIntroduce.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIntroduce.setForeground(new java.awt.Color(0, 255, 255));
        lblIntroduce.setText("Introduce");
        getContentPane().add(lblIntroduce, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 200, 30));

        lblPIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPIN.setForeground(new java.awt.Color(0, 255, 255));
        lblPIN.setText("tu PIN secreto:");
        getContentPane().add(lblPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DEL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 40, 20));

        lblCajero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCajero.setForeground(new java.awt.Color(255, 255, 255));
        lblCajero.setText("CAJERO ATM");
        getContentPane().add(lblCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, 30));

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        btnRetroceder.setBackground(new java.awt.Color(255, 255, 255));
        btnRetroceder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRetroceder.setForeground(new java.awt.Color(0, 0, 0));
        btnRetroceder.setText("Retroceder");
        btnRetroceder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        jPanel2.add(btnRetroceder);

        btnAcceder.setBackground(new java.awt.Color(51, 255, 204));
        btnAcceder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(0, 0, 0));
        btnAcceder.setText("Acceder");
        btnAcceder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        jPanel2.add(btnAcceder);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 200, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_cajero.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 350));

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 40, 30));

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 40, 30));

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 30, 30));

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 40, 30));

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 40, 30));

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 40, 30));

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 40, 30));

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 40, 30));

        btn9.setText("jButton1");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 40, -1));

        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 40, 20));

        btnAsterisco.setText("jButton1");
        btnAsterisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsteriscoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsterisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 30, -1));

        btnBorrar.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 40, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        Introducir_Tarjeta Introducir_Tarjeta = new Introducir_Tarjeta(idioma);
        Introducir_Tarjeta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        Connection conexion = Conexion.mySQL("proyecto_final", "root", "");
        if (conexion == null) {
        JOptionPane.showMessageDialog(null, "Conexión no establecida");
        System.exit(0);
        }else{
            try {
                char[] pinIntroducido=txfPIN.getPassword();

                if (pinIntroducido.length==0) {
                    JOptionPane.showMessageDialog(null, "Debe introducir un pin", "Error",JOptionPane.ERROR_MESSAGE);
                } else {
                    //Pasar la cadena de caracteres de la contraseña a string para hacer la consulta en la bbdd
                    String sPinIntroducido= new String(pinIntroducido);
                    Statement sentencia = conexion.createStatement();
                    String sql = "SELECT clientes.Nombre, clientes.ID_Cliente, tarjetas_de_credito.ID_Tarjeta, tarjetas_de_credito.PIN FROM clientes JOIN tarjetas_de_credito ON clientes.ID_Cliente = tarjetas_de_credito.ID_Cliente WHERE PIN = '"+sPinIntroducido+"' AND ID_Tarjeta = '"+this.ID_Tarjeta+"';";
                    ResultSet resultado_usuario = sentencia.executeQuery(sql);
                    if (resultado_usuario.next()) {
                        String id_usuario = resultado_usuario.getString("ID_Cliente");
                        String nombre = resultado_usuario.getString("Nombre");
                        String numTarjeta = resultado_usuario.getString("ID_Tarjeta");
                        int pin = resultado_usuario.getInt("PIN");
                        JOptionPane.showMessageDialog(null, "Se ha conectado correctamente");
                        Sesion sesion_usuario = new Sesion(id_usuario,nombre,numTarjeta,pin,this,this.idioma);
                        Opciones_usuario Opciones_usuario = new Opciones_usuario(sesion_usuario);
                        Opciones_usuario.setVisible(true);
                        this.dispose();
                    } else {
                        if (intentos == 0) {
                            Statement sentenciaBloqueo = conexion.createStatement();
                            String sqlBloqueo = "UPDATE tarjetas_de_credito SET Bloqueada = 1 WHERE ID_Tarjeta = '"+this.ID_Tarjeta+"';";
                            int resultadoBloqueo = sentenciaBloqueo.executeUpdate(sqlBloqueo);
                            if(resultadoBloqueo>0){
                            JOptionPane.showMessageDialog(null, "Tarjeta bloqueada por exceso de intentos. El programa se cerrará.");
                            System.exit(0);
                            }
                        }
                        JOptionPane.showMessageDialog(null, "El PIN es incorrecto. Le quedan "+intentos+" intentos.");
                        intentos--;
                        txfPIN.setText("");
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la consulta");
            }
        }
    }//GEN-LAST:event_btnAccederActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String cadena= txfPIN.getText();
        try{
            String nueva_cadena = cadena.substring(0, cadena.length() - 1);
            txfPIN.setText(nueva_cadena);
        }catch(StringIndexOutOfBoundsException e){

        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAsteriscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsteriscoActionPerformed
        String cadena= txfPIN.getText();
        txfPIN.setText(cadena+".");
    }//GEN-LAST:event_btnAsteriscoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Introducir_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Introducir_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Introducir_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Introducir_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnAsterisco;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCajero;
    private javax.swing.JLabel lblIntroduce;
    private javax.swing.JLabel lblPIN;
    private javax.swing.JPasswordField txfPIN;
    // End of variables declaration//GEN-END:variables
    private int intentos=2;
    private String ID_Tarjeta;
    private Idioma idioma;
}
