/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cajero;
import Conexion_bd.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class Introducir_Tarjeta extends javax.swing.JFrame {

    /**
     * Creates new form Introducir_Tarjeta
     */
    public Introducir_Tarjeta(Idioma idioma) {
        initComponents();
        this.idioma=idioma;
        cargarIdioma(idioma);
    }
    public void cargarIdioma(Idioma idioma){
        Properties propiedades = new Idioma(idioma.getNombre());
        this.setTitle(propiedades.getProperty("Introducir_Tarjeta"));
        lblIntroduce.setText(propiedades.getProperty("Introduce"));
        lblTarjeta.setText(propiedades.getProperty("Tarjeta"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetroceder = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblTarjeta = new javax.swing.JLabel();
        btnTarjeta = new javax.swing.JButton();
        txfNumeroTarjeta = new javax.swing.JTextField();
        lblIntroduce = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnToggleAbajo = new javax.swing.JToggleButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAsterisco = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Introducir Tarjeta");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetroceder.setBackground(new java.awt.Color(0, 0, 0));
        btnRetroceder.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha.png"))); // NOI18N
        btnRetroceder.setContentAreaFilled(false);
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 40, 40));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DEL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 40, 20));

        lblTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTarjeta.setForeground(new java.awt.Color(0, 255, 255));
        lblTarjeta.setText("de la tarjeta");
        getContentPane().add(lblTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 200, 30));

        btnTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta3.png"))); // NOI18N
        btnTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTarjetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarjetaMouseExited(evt);
            }
        });
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 160, 90));
        getContentPane().add(txfNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 200, -1));

        lblIntroduce.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIntroduce.setForeground(new java.awt.Color(0, 255, 255));
        lblIntroduce.setText("Introduce el numero");
        getContentPane().add(lblIntroduce, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_cajero.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 350));

        btnToggleAbajo.setText("jToggleButton1");
        btnToggleAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleAbajoActionPerformed(evt);
            }
        });
        getContentPane().add(btnToggleAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 120, 40));

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 40, 30));

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 40, 30));

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 30, 30));

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 40, 30));

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 40, 30));

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 40, 30));

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 40, 30));

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 40, 30));

        btn9.setText("jButton1");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 40, -1));

        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 40, 20));

        btnBorrar.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 40, 30));

        btnAsterisco.setText("jButton1");
        btnAsterisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsteriscoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsterisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 30, -1));

        btnAdmin.setText("jButton1");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        try {   
        Connection conexion =  conexion=Conexion.mySQL("proyecto_final", "root", "");
        if (conexion == null) {
        JOptionPane.showMessageDialog(null, "Conexión no establecida");
        System.exit(0);
        }else{
        Statement sentencia= conexion.createStatement();
        String sql = "SELECT Bloqueada FROM tarjetas_de_credito WHERE ID_tarjeta = "+txfNumeroTarjeta.getText()+"";
        ResultSet resultado= sentencia.executeQuery(sql);
        if(resultado.next()){
            int numBloq = resultado.getInt("Bloqueada");
            if(numBloq==0){
                Introducir_PIN Introducir_PIN = new Introducir_PIN(txfNumeroTarjeta.getText(),this.idioma);
                Introducir_PIN.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "La tarjeta se encuentra bloqueada, acude a la sucursal para desbloquearla.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error, no existe ninguna tarjeta con ese numero","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTarjetaActionPerformed
    
    private void btnTarjetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarjetaMouseEntered
        btnTarjeta.setBounds(430,260,160,75);
    }//GEN-LAST:event_btnTarjetaMouseEntered

    private void btnTarjetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarjetaMouseExited
        btnTarjeta.setBounds(430,260,160,105);
    }//GEN-LAST:event_btnTarjetaMouseExited

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        try{
        String nueva_cadena = cadena.substring(0, cadena.length() - 1);
        txfNumeroTarjeta.setText(nueva_cadena);
        }catch(StringIndexOutOfBoundsException e){
            
        } 
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAsteriscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsteriscoActionPerformed
        String cadena= txfNumeroTarjeta.getText();
        txfNumeroTarjeta.setText(cadena+".");
    }//GEN-LAST:event_btnAsteriscoActionPerformed

    private void btnToggleAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleAbajoActionPerformed
        
    }//GEN-LAST:event_btnToggleAbajoActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
       try {
            Connection conexion = Conexion.mySQL("proyecto_final", "root", "");
            Statement sentencia= conexion.createStatement();
            String sql = "SELECT * FROM administradores WHERE Contrasena = "+txfNumeroTarjeta.getText()+"";
            ResultSet resultado = sentencia.executeQuery(sql);
            
                if(resultado.next() && btnToggleAbajo.isSelected()== true){
                    try{
                        Connection conexion_admin = Conexion.mySQL("proyecto_final", "root", "");
                        Statement sentencia_admin= conexion_admin.createStatement();
                        String sql_admin = "SELECT * FROM administradores WHERE Contrasena = "+txfNumeroTarjeta.getText()+"";
                        ResultSet resultado_admin = sentencia.executeQuery(sql_admin);
                        int contador=0;
                            if(resultado_admin.next()){
                                contador = resultado_admin.getInt(1);
                            }
                            if(contador>0){
                                int id = resultado_admin.getInt("ID_Administrador");
                                String nombre = resultado_admin.getString("Nombre");
                                String contrasena = resultado_admin.getString("Contrasena");
                                Sesion sesion_admin = new Sesion(id,nombre,contrasena);
                                Opciones_admin Opciones_admin = new Opciones_admin(sesion_admin);
                                Opciones_admin.setVisible(true);
                                this.dispose();
                            }else{
                                JOptionPane.showMessageDialog(this, "Error 0","Error", JOptionPane.ERROR_MESSAGE);
                            }
                    }catch(SQLException ex) {
                        System.out.println(ex.getMessage());
                        JOptionPane.showMessageDialog(this, "Error 1","Error", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Error 2","Error", JOptionPane.ERROR_MESSAGE);
                }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 3","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        Inicio Inicio = new Inicio();
        Inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Introducir_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Introducir_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Introducir_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Introducir_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Introducir_Tarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAsterisco;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JToggleButton btnToggleAbajo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIntroduce;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JTextField txfNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
    private Idioma idioma;
}
